# Generated by Django 2.2.10 on 2021-03-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_auto_20210330_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskslist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='taskslist',
            name='name',
        ),
    ]
